import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

type Locale = "nl" | "en";

const translations = {
  nl: {
    common: {
      marketingPlatform: "Marketing Platform",
      language: "Taal",
      dutch: "Nederlands",
      english: "English",
      save: "Opslaan",
      edit: "Bewerken",
      add: "Toevoegen",
      remove: "Verwijderen",
      search: "Zoeken",
      website: "Website",
      choosePlatform: "Kies platform",
      allPlatforms: "Alle platformen",
      today: "Vandaag",
      yesterday: "Gisteren",
    },
    nav: {
      dashboard: "Dashboard",
      automations: "Automations",
      messages: "Berichten",
      contacts: "Contacten",
      broadcasts: "Bulkberichten",
      contentCalendar: "Content Kalender",
      groupChat: "Groepschat",
      team: "Team",
      settings: "Instellingen",
    },
    dashboard: {
      welcome: "Welkom bij je marketing platform.",
      gettingStarted: "Aan de slag",
      gettingStartedBody: "Gebruik het menu links om je automations, contacten, bulkberichten en meer te beheren.",
      overview: "Overzicht",
      overviewBody: "Voeg je bedrijfsinformatie toe via de instellingen om aan de slag te gaan.",
    },
    messages: {
      title: "Berichten",
      new: "nieuw",
      all: "Alle",
      connectAccount: "Account koppelen",
      connectAccountTitle: "Social Media Account Koppelen",
      platform: "Platform",
      username: "Gebruikersnaam",
      displayName: "Weergavenaam",
      connectHint: "Dit koppelt de UI aan jouw account. Voor echte DM-integratie zijn API-keys nodig via de platforminstellingen.",
      accountConnected: "Account gekoppeld",
      accountDisconnected: "Account ontkoppeld",
      messageSent: "Bericht verstuurd",
      demoConversationCreated: "Demo gesprek aangemaakt",
      noConversationTitle: "Nog geen gesprek geselecteerd",
      noConversationBody: "Koppel een account en open of maak een gesprek om berichten te versturen.",
      replyPlaceholder: "Typ je antwoord...",
      send: "Versturen",
      yesterday: "Gisteren",
    },
    contacts: {
      title: "Contacten",
      subtitle: "Beheer je subscribers en contacten van social media.",
      addContact: "Contact toevoegen",
      editContact: "Contact bewerken",
      newContact: "Nieuw contact",
      name: "Naam",
      username: "Gebruikersnaam",
      platform: "Platform",
      tags: "Tags (komma-gescheiden)",
      source: "Bron",
      totalContacts: "Totaal contacten",
      searchPlaceholder: "Zoek contact...",
      filterByTag: "Filter op tag",
      allTags: "Alle tags",
      noContacts: "Geen contacten",
      noContactsBody: "Voeg contacten toe of laat ze automatisch aanmaken via je automation flows.",
      updated: "Contact bijgewerkt",
      created: "Contact toegevoegd",
      deleted: "Contact verwijderd",
      manual: "Handmatig",
      justNow: "Zojuist",
    },
    broadcasts: {
      title: "Bulkberichten",
      subtitle: "Stuur in één keer een bericht naar meerdere contacten via DM.",
      newBroadcast: "Nieuw bulkbericht",
      editBroadcast: "Bulkbericht bewerken",
      name: "Naam",
      message: "Bericht",
      platform: "Platform",
      audience: "Doelgroep / Tag",
      schedule: "Inplannen (optioneel)",
      sent: "Verstuurd",
      scheduled: "Ingepland",
      draft: "Concept",
      emptyTitle: "Geen bulkberichten",
      emptyBody: "Maak een bulkbericht om in één keer een bericht naar meerdere contacten te sturen.",
      firstBroadcast: "Eerste bulkbericht",
      sendNow: "Nu versturen",
      updated: "Bulkbericht bijgewerkt",
      created: "Bulkbericht aangemaakt",
      deleted: "Bulkbericht verwijderd",
      allContacts: "Alle contacten",
    },
    calendar: {
      title: "Content Kalender",
      subtitle: "Plan en beheer je social media content.",
      events: "Events",
      fillFields: "Vul alle velden in",
      eventUpdated: "Event bijgewerkt",
      eventAdded: "Event toegevoegd",
      eventDeleted: "Event verwijderd",
      editEvent: "Event bewerken",
      addEvent: "Event toevoegen",
      existingEvents: "Bestaande events:",
      eventTitle: "Titel",
      time: "Tijd",
      more: "meer",
    },
    groupChat: {
      title: "Groepschat",
      subtitle: "Interne teamcommunicatie",
      channels: "Kanalen",
      newChannel: "Nieuw kanaal",
      channelName: "Kanaal naam",
      channelDescription: "Beschrijving",
      createChannel: "Kanaal aanmaken",
      online: "Online",
      noMessages: "Nog geen berichten in",
      sendFirstMessage: "Stuur het eerste bericht!",
      messagePlaceholder: "Bericht in",
      you: "Jij",
      createHint: "Waar gaat dit kanaal over?",
      send: "Verstuur",
      nameRequired: "Geef het kanaal een naam",
      channelCreated: "Kanaal aangemaakt",
      channelDeleted: "Kanaal verwijderd",
      readyForUse: "is klaar voor gebruik.",
      removed: "is verwijderd.",
      defaultDescription: "Nieuw kanaal",
      channelNamePlaceholder: "bijv. social-media",
      channelsData: {
        socialMedia: "Posts, planning en performance op social kanalen",
        ads: "Meta, Google en TikTok advertenties",
        emailMarketing: "Nieuwsbrieven, flows en verzendmomenten",
        seoWebsite: "Organisch verkeer, landingspagina's en website-optimalisatie",
      },
    },
    team: {
      title: "Team",
      subtitle: "Je marketing team overzicht.",
      addMember: "Lid toevoegen",
      newMember: "Nieuw teamlid",
      name: "Naam",
      role: "Rol",
      email: "E-mail",
      fillFields: "Vul alle velden in",
      memberAdded: "Teamlid toegevoegd",
      memberDeleted: "Teamlid verwijderd",
    },
    settings: {
      title: "Instellingen",
      subtitle: "Beheer je account en platform instellingen.",
      companyProfile: "Bedrijfsprofiel",
      companyName: "Bedrijfsnaam",
      notifications: "Notificaties",
      branding: "Branding",
      channels: "Social Media Kanalen",
      slogan: "Slogan",
      primaryColor: "Hoofdkleur",
      emailNotifications: "E-mail notificaties",
      emailNotificationsDesc: "Ontvang meldingen per e-mail",
      pushNotifications: "Push notificaties",
      pushNotificationsDesc: "Browser push meldingen",
      weeklyReport: "Wekelijks rapport",
      weeklyReportDesc: "Automatisch wekelijks overzicht",
      campaignAlerts: "Campagne alerts",
      campaignAlertsDesc: "Meldingen bij campagne wijzigingen",
      profileSaved: "Profiel opgeslagen",
      brandingSaved: "Branding opgeslagen",
      channelsSaved: "Kanalen opgeslagen",
      turnedOn: "ingeschakeld",
      turnedOff: "uitgeschakeld",
      logoUrl: "Logo URL",
    },
    notFound: {
      message: "Oops! Pagina niet gevonden",
      returnHome: "Terug naar dashboard",
    },
    messagesPanel: {
      connectedAccounts: "Gekoppelde accounts",
      searchConversation: "Zoek gesprek...",
      noAccounts: "Geen accounts gekoppeld",
      noAccountsBody: "Koppel je Instagram- of TikTok-account om DM's te beheren",
      noConversations: "Geen gesprekken gevonden",
      conversationDeleted: "Gesprek verwijderd",
      replyVia: "Antwoord via",
      selectConversation: "Selecteer een gesprek",
      startByConnecting: "of koppel een social media account om te beginnen",
    },
  },
  en: {
    common: {
      marketingPlatform: "Marketing Platform",
      language: "Language",
      dutch: "Dutch",
      english: "English",
      save: "Save",
      edit: "Edit",
      add: "Add",
      remove: "Remove",
      search: "Search",
      website: "Website",
      choosePlatform: "Choose platform",
      allPlatforms: "All platforms",
      today: "Today",
      yesterday: "Yesterday",
    },
    nav: {
      dashboard: "Dashboard",
      automations: "Automations",
      messages: "Messages",
      contacts: "Contacts",
      broadcasts: "Bulk Messages",
      contentCalendar: "Content Calendar",
      groupChat: "Group Chat",
      team: "Team",
      settings: "Settings",
    },
    dashboard: {
      welcome: "Welcome to your marketing platform.",
      gettingStarted: "Getting started",
      gettingStartedBody: "Use the menu on the left to manage your automations, contacts, bulk messages, and more.",
      overview: "Overview",
      overviewBody: "Add your company information in settings to get started.",
    },
    messages: {
      title: "Messages",
      new: "new",
      all: "All",
      connectAccount: "Connect account",
      connectAccountTitle: "Connect Social Media Account",
      platform: "Platform",
      username: "Username",
      displayName: "Display name",
      connectHint: "This connects the UI to your account. Real DM integration still requires API keys in platform settings.",
      accountConnected: "Account connected",
      accountDisconnected: "Account disconnected",
      messageSent: "Message sent",
      demoConversationCreated: "Demo conversation created",
      noConversationTitle: "No conversation selected yet",
      noConversationBody: "Connect an account and open or create a conversation to send messages.",
      replyPlaceholder: "Type your reply...",
      send: "Send",
      yesterday: "Yesterday",
    },
    contacts: {
      title: "Contacts",
      subtitle: "Manage your subscribers and social media contacts.",
      addContact: "Add contact",
      editContact: "Edit contact",
      newContact: "New contact",
      name: "Name",
      username: "Username",
      platform: "Platform",
      tags: "Tags (comma-separated)",
      source: "Source",
      totalContacts: "Total contacts",
      searchPlaceholder: "Search contact...",
      filterByTag: "Filter by tag",
      allTags: "All tags",
      noContacts: "No contacts",
      noContactsBody: "Add contacts or let them be created automatically through your automation flows.",
      updated: "Contact updated",
      created: "Contact added",
      deleted: "Contact removed",
      manual: "Manual",
      justNow: "Just now",
    },
    broadcasts: {
      title: "Bulk Messages",
      subtitle: "Send one message to multiple contacts at once via DM.",
      newBroadcast: "New bulk message",
      editBroadcast: "Edit bulk message",
      name: "Name",
      message: "Message",
      platform: "Platform",
      audience: "Audience / Tag",
      schedule: "Schedule (optional)",
      sent: "Sent",
      scheduled: "Scheduled",
      draft: "Draft",
      emptyTitle: "No bulk messages",
      emptyBody: "Create a bulk message to send one message to multiple contacts at once.",
      firstBroadcast: "First bulk message",
      sendNow: "Send now",
      updated: "Bulk message updated",
      created: "Bulk message created",
      deleted: "Bulk message deleted",
      allContacts: "All contacts",
    },
    calendar: {
      title: "Content Calendar",
      subtitle: "Plan and manage your social media content.",
      events: "Events",
      fillFields: "Fill in all fields",
      eventUpdated: "Event updated",
      eventAdded: "Event added",
      eventDeleted: "Event deleted",
      editEvent: "Edit event",
      addEvent: "Add event",
      existingEvents: "Existing events:",
      eventTitle: "Title",
      time: "Time",
      more: "more",
    },
    groupChat: {
      title: "Group Chat",
      subtitle: "Internal team communication",
      channels: "Channels",
      newChannel: "New channel",
      channelName: "Channel name",
      channelDescription: "Description",
      createChannel: "Create channel",
      online: "Online",
      noMessages: "No messages yet in",
      sendFirstMessage: "Send the first message!",
      messagePlaceholder: "Message in",
      you: "You",
      createHint: "What is this channel about?",
      send: "Send",
      nameRequired: "Give the channel a name",
      channelCreated: "Channel created",
      channelDeleted: "Channel deleted",
      readyForUse: "is ready to use.",
      removed: "has been removed.",
      defaultDescription: "New channel",
      channelNamePlaceholder: "e.g. social-media",
      channelsData: {
        socialMedia: "Posts, planning, and social channel performance",
        ads: "Meta, Google, and TikTok ads",
        emailMarketing: "Newsletters, flows, and send timing",
        seoWebsite: "Organic traffic, landing pages, and website optimization",
      },
    },
    team: {
      title: "Team",
      subtitle: "Overview of your marketing team.",
      addMember: "Add member",
      newMember: "New team member",
      name: "Name",
      role: "Role",
      email: "Email",
      fillFields: "Fill in all fields",
      memberAdded: "Team member added",
      memberDeleted: "Team member removed",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account and platform settings.",
      companyProfile: "Company profile",
      companyName: "Company name",
      notifications: "Notifications",
      branding: "Branding",
      channels: "Social Media Channels",
      slogan: "Slogan",
      primaryColor: "Primary color",
      emailNotifications: "Email notifications",
      emailNotificationsDesc: "Receive updates by email",
      pushNotifications: "Push notifications",
      pushNotificationsDesc: "Browser push notifications",
      weeklyReport: "Weekly report",
      weeklyReportDesc: "Automatic weekly summary",
      campaignAlerts: "Campaign alerts",
      campaignAlertsDesc: "Notifications when campaigns change",
      profileSaved: "Profile saved",
      brandingSaved: "Branding saved",
      channelsSaved: "Channels saved",
      turnedOn: "enabled",
      turnedOff: "disabled",
      logoUrl: "Logo URL",
    },
    notFound: {
      message: "Oops! Page not found",
      returnHome: "Return to dashboard",
    },
    messagesPanel: {
      connectedAccounts: "Connected accounts",
      searchConversation: "Search conversation...",
      noAccounts: "No accounts connected",
      noAccountsBody: "Connect your Instagram or TikTok account to manage DMs",
      noConversations: "No conversations found",
      conversationDeleted: "Conversation deleted",
      replyVia: "Reply via",
      selectConversation: "Select a conversation",
      startByConnecting: "or connect a social media account to get started",
    },
  },
} as const;

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function getTranslation(locale: Locale, key: string) {
  const value = key.split(".").reduce<unknown>((acc, part) => {
    if (acc && typeof acc === "object" && part in acc) {
      return (acc as Record<string, unknown>)[part];
    }
    return undefined;
  }, translations[locale]);

  return typeof value === "string" ? value : key;
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocale] = useState<Locale>(() => {
    const saved = localStorage.getItem("app-locale");
    return saved === "en" ? "en" : "nl";
  });

  useEffect(() => {
    localStorage.setItem("app-locale", locale);
  }, [locale]);

  const value = useMemo(
    () => ({
      locale,
      setLocale,
      t: (key: string) => getTranslation(locale, key),
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
